# Generated by Django 3.2.11 on 2024-01-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childbot',
            name='campaign',
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='childbots',
            field=models.ManyToManyField(to='sessionbot.ChildBot'),
        ),
    ]
