# Generated by Django 3.2 on 2024-10-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='067b9e0a-8af3-11ef-b310-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='067b9e0a-8af3-11ef-b310-047c1611323a', max_length=50000, unique=True),
        ),
    ]
