# Generated by Django 3.2.11 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0002_auto_20240116_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='os',
            field=models.CharField(choices=[('android', 'Android'), ('browser', 'Browser')], default='android', max_length=5000),
        ),
    ]
