# Generated by Django 3.2 on 2024-10-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0003_auto_20241015_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c179ed49-8af6-11ef-9823-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c179ed49-8af6-11ef-9823-047c1611323a', max_length=50000, unique=True),
        ),
    ]
