# Generated by Django 3.2.11 on 2024-01-16 12:49

from django.db import migrations, models
import sessionbot.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0003_bulkcampaign_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='devices',
            field=models.ManyToManyField(to='sessionbot.Device'),
        ),
       
    ]
