# Generated by Django 3.2.11 on 2024-01-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0004_auto_20240116_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcampaign',
            name='activity_to_perform',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('like', 'like'), ('dm', 'dm'), ('like_comment', 'like_comment'), ('reply_to_comment', 'reply_to_comment'), ('follow', 'follow'), ('login', 'login'), ('retweet', 'retweet'), ('share_post', 'share post')], max_length=100, null=True),
        ),
    ]
