# Generated by Django 3.2 on 2024-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0005_auto_20241022_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='6e4e006e-9058-11ef-8f58-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='6e4e006e-9058-11ef-8f58-047c1611323a', max_length=50000, unique=True),
        ),
    ]
