# Generated by Django 3.2.11 on 2024-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0005_alter_bulkcampaign_activity_to_perform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_host',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_username',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
