# Generated by Django 3.2.11 on 2024-01-20 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sessionbot', '0006_auto_20240120_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5000, null=True)),
                ('instance_id', models.CharField(max_length=500, null=True)),
                ('public_ip', models.URLField(blank=True, max_length=100, null=True)),
                ('instance_type', models.CharField(choices=[('main', 'Main'), ('data_server', 'DataServer'), ('login_server', 'LoginServer'), ('worker_server', 'WorkerServer'), ('dev_server', 'DevelopmentServer')], max_length=500)),
                ('state', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped'), ('pending', 'pending'), ('shutting-down', 'shutting-down'), ('terminated', 'terminated'), ('stopping', 'stopping'), ('starting', 'starting'), ('backing_up', 'backing_up'), ('rebooting', 'Rebooting'), ('service_offline', 'Service Offline')], default='pending', max_length=500)),
                ('online_status', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline', max_length=500)),
                ('running_process_count', models.IntegerField(default=0)),
                ('task_queue_count', models.IntegerField(default=0)),
                ('last_heart_beat', models.DateTimeField(blank=True, null=True)),
                ('ram_usage', models.IntegerField(default=0)),
                ('disk_usage', models.IntegerField(default=0)),
                ('tm_state', models.CharField(blank=True, choices=[('ACTIVE', 'Runing'), ('IN_ACTIVE', 'Restarting'), ('RESTART', 'Restarting')], max_length=10, null=True)),
                ('localstore_active', models.BooleanField(default=False)),
                ('access_secret_key', models.CharField(blank=True, max_length=5000, null=True, unique=True)),
                ('maximum_parallel_tasks_allowed', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
            options={
                'verbose_name': 'server',
            },
        ),
    ]
