# Generated by Django 3.2 on 2024-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0006_auto_20241022_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='ae5797af-909f-11ef-aa07-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ae5797af-909f-11ef-aa07-047c1611323a', max_length=50000, unique=True),
        ),
    ]
