# Generated by Django 3.2.11 on 2024-01-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sessionbot', '0007_ec2instance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EC2Instance',
            new_name='Server',
        ),
    ]
