# Generated by Django 3.2 on 2024-10-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0007_auto_20241022_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childbot',
            name='email_address',
            field=models.EmailField(blank=True, db_index=True, default='none@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='childbot',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='childbot',
            name='recovery_email',
            field=models.EmailField(blank=True, default='none@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='63c03a07-9120-11ef-9f54-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='63c03a07-9120-11ef-9f54-047c1611323a', max_length=50000, unique=True),
        ),
    ]
