# Generated by Django 3.2.11 on 2024-01-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0008_rename_ec2instance_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connected_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessionbot.server'),
        ),
    ]
