# Generated by Django 3.2 on 2024-10-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0008_auto_20241023_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c534e417-9120-11ef-9a10-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c534e417-9120-11ef-9a10-047c1611323a', max_length=50000, unique=True),
        ),
    ]
