# Generated by Django 3.2.11 on 2024-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0009_device_connected_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='connected_to',
            new_name='connected_to_server',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
