# Generated by Django 3.2 on 2024-10-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0009_auto_20241023_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childbot',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://th.bing.com/th/id/R.363f7e495d2d2e4f1407657b52c37cdb?rik=wCUstSresWmNMA&pid=ImgRaw&r=0', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c5f2707b-9121-11ef-8e7d-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c5f2707b-9121-11ef-8e7d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
