# Generated by Django 3.2.11 on 2024-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0010_auto_20240120_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
