# Generated by Django 3.2 on 2024-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0010_auto_20241023_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childbot',
            name='cookie',
            field=models.FileField(blank=True, default='https://gist.github.com/mrunkel/7f16fad35250da476ab0cc58aebde7ec', null=True, upload_to='login/cookies'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='9836c99b-9122-11ef-923a-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='9836c99b-9122-11ef-923a-047c1611323a', max_length=50000, unique=True),
        ),
    ]
