# Generated by Django 3.2.11 on 2024-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0011_alter_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetask',
            name='input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
