# Generated by Django 3.2 on 2024-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0011_auto_20241023_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbot',
            name='challenged',
            field=models.BooleanField(default=False, help_text='Indicates if the bot is currently challenged.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='31c55000-912e-11ef-9f3e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='31c55000-912e-11ef-9f3e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
