# Generated by Django 3.2.11 on 2024-01-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sessionbot', '0012_scrapetask_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_threads', models.IntegerField(default=1)),
                ('proxy_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ua_string', models.CharField(max_length=5000, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('proxy_country', models.CharField(max_length=100, null=True)),
                ('proxy_city', models.CharField(max_length=100, null=True)),
                ('proxy_blacklisted', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_user', models.PositiveIntegerField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tagged_bad_on', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('proxy_type', models.CharField(choices=[('static_proxy', 'Static Proxy'), ('rotating_proxy', 'Rotating Proxy')], default='static_proxy', max_length=20)),
                ('proxy_protocol', models.CharField(choices=[('http', 'Http'), ('socks', 'Socks'), ('http_socks', 'Both')], default='http', max_length=20)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_proxy', to='sessionbot.bulkcampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('scrape_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_task_proxy', to='sessionbot.scrapetask')),
            ],
            options={
                'verbose_name_plural': 'proxies',
                'unique_together': {('customer', 'proxy_url')},
            },
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='proxies',
            field=models.ManyToManyField(related_name='proxies', to='sessionbot.Proxy'),
        ),
    ]
