# Generated by Django 3.2.11 on 2024-01-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0013_auto_20240122_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_list', models.TextField(blank=True, null=True)),
                ('influencer_profile', models.TextField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('followup_message', models.TextField(blank=True, null=True)),
                ('reachout_message', models.TextField(blank=True, null=True)),
                ('response_to_reachout_message', models.TextField(blank=True, null=True)),
                ('target_hashtag', models.TextField(blank=True, null=True)),
                ('target_location', models.JSONField(blank=True, null=True)),
                ('message_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='comment_list',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='followup_message',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='influencer_profile',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='message_list',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='reachout_message',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='response_to_reachout_message',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='target_hashtag',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='target_list',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='target_location',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='welcome_message',
        ),
        migrations.CreateModel(
            name='DemoGraphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, unique=True)),
                ('scrape_tasks', models.ManyToManyField(to='sessionbot.ScrapeTask')),
            ],
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='demographic',
            field=models.ManyToManyField(to='sessionbot.DemoGraphic'),
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='text_content',
            field=models.ManyToManyField(to='sessionbot.CampaignTextContent'),
        ),
    ]
