# Generated by Django 3.2 on 2024-10-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0013_auto_20241023_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='fe955478-9137-11ef-92a2-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='fe955478-9137-11ef-92a2-047c1611323a', max_length=50000, unique=True),
        ),
    ]
