# Generated by Django 3.2 on 2024-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0014_auto_20241023_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='4810bd12-913d-11ef-b731-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4810bd12-913d-11ef-b731-047c1611323a', max_length=50000, unique=True),
        ),
    ]
