# Generated by Django 3.2.11 on 2024-01-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0014_auto_20240122_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkcampaign',
            old_name='text_content',
            new_name='messaging',
        ),
    ]
