# Generated by Django 3.2.11 on 2024-01-22 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0015_rename_text_content_bulkcampaign_messaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start_time')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
                ('delay_range', models.CharField(blank=True, max_length=20, null=True)),
                ('max_interactions_per_runtask', models.IntegerField(default=5)),
                ('delay_between_runtasks', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('behavior', models.JSONField(default={'follow_per_session': 10, 'with_commenter': 'like_comment', 'with_liker': 'like', 'with_new_followers': 'welocome_message,like_3,comment_3,share_post', 'with_target': 'follow'})),
                ('max_scrape_bots', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='delay_between_runtasks',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='delay_range',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='max_interactions_per_runtask',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='max_scrape_bots',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='start_time',
        ),
    ]
