# Generated by Django 3.2.11 on 2024-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0016_auto_20240122_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='settings',
            field=models.ManyToManyField(to='sessionbot.Settings'),
        ),
    ]
