# Generated by Django 3.2.11 on 2024-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0017_bulkcampaign_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('target_posts', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='target_post',
        ),
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='username_of_comment_owner',
        ),
    ]
