# Generated by Django 3.2 on 2024-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0017_auto_20241024_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='171a577b-91fb-11ef-8a6f-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='171a577b-91fb-11ef-8a6f-047c1611323a', max_length=50000, unique=True),
        ),
    ]
