# Generated by Django 3.2.11 on 2024-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0018_auto_20240122_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='sharing',
            field=models.ManyToManyField(to='sessionbot.Sharing'),
        ),
    ]
