# Generated by Django 3.2 on 2024-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0018_auto_20241024_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='b9b230c5-91ff-11ef-a3d1-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='b9b230c5-91ff-11ef-a3d1-047c1611323a', max_length=50000, unique=True),
        ),
    ]
