# Generated by Django 3.2 on 2024-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0019_auto_20241024_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='4213778b-9214-11ef-9890-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4213778b-9214-11ef-9890-047c1611323a', max_length=50000, unique=True),
        ),
    ]
