# Generated by Django 3.2.11 on 2024-01-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0019_bulkcampaign_sharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaigntextcontent',
            name='name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
