# Generated by Django 3.2.11 on 2024-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0020_auto_20240122_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentActivity',
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='activity_to_perform',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='sharing',
            field=models.ManyToManyField(null=True, to='sessionbot.Sharing'),
        ),
    ]
