# Generated by Django 3.2 on 2024-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0020_auto_20241024_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='dde67ad3-9225-11ef-844e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='dde67ad3-9225-11ef-844e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
