# Generated by Django 3.2.11 on 2024-01-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0021_auto_20240122_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessionbot.server'),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='childbots',
            field=models.ManyToManyField(related_name='campaign', to='sessionbot.ChildBot'),
        ),
    ]
