# Generated by Django 3.2 on 2024-10-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0021_auto_20241024_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='22d0dc7b-9228-11ef-b02d-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='22d0dc7b-9228-11ef-b02d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
