# Generated by Django 3.2 on 2024-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0022_auto_20241024_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='0cf9e2f1-922f-11ef-aed1-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='0cf9e2f1-922f-11ef-aed1-047c1611323a', max_length=50000, unique=True),
        ),
    ]
