# Generated by Django 3.2.11 on 2024-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0022_auto_20240122_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childbot',
            name='scrape_tasks',
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='childbots',
            field=models.ManyToManyField(related_name='scrape_task', to='sessionbot.ChildBot'),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='os',
            field=models.CharField(choices=[('android', 'Android'), ('browser', 'Browser')], default='android', max_length=5000),
        ),
    ]
