# Generated by Django 3.2.11 on 2024-02-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0023_auto_20240218_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='profiles',
        ),
        migrations.AddField(
            model_name='childbot',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessionbot.device'),
        ),
    ]
