# Generated by Django 3.2.11 on 2024-03-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0024_auto_20240221_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='last_user',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_city',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_country',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='scrape_task',
        ),
    ]
