# Generated by Django 3.2 on 2024-10-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0024_auto_20241024_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='e31aa119-9235-11ef-b026-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='e31aa119-9235-11ef-b026-047c1611323a', max_length=50000, unique=True),
        ),
    ]
