# Generated by Django 3.2.11 on 2024-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0025_auto_20240315_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('music', models.URLField(blank=True)),
                ('file', models.FileField(upload_to='todos/')),
                ('bots', models.ManyToManyField(to='sessionbot.ChildBot')),
            ],
        ),
    ]
