# Generated by Django 3.2 on 2024-10-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0026_auto_20241025_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='d667406e-9376-11ef-a745-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='d667406e-9376-11ef-a745-047c1611323a', max_length=50000, unique=True),
        ),
    ]
