# Generated by Django 3.2.11 on 2024-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0026_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.FileField(upload_to='media/todos/'),
        ),
    ]
