# Generated by Django 3.2.11 on 2024-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0027_alter_todo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='location',
            field=models.CharField(blank=True, max_length=2550),
        ),
        migrations.AlterField(
            model_name='todo',
            name='music',
            field=models.CharField(blank=True, max_length=2550),
        ),
    ]
