# Generated by Django 3.2 on 2024-10-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0027_auto_20241026_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='servers',
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='servers',
            field=models.ManyToManyField(blank=True, null=True, to='sessionbot.Server'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='a9e88611-9378-11ef-b4b4-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='a9e88611-9378-11ef-b4b4-047c1611323a', max_length=50000, unique=True),
        ),
    ]
