# Generated by Django 3.2.11 on 2024-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0028_auto_20240316_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, unique=True)),
                ('should_have_highlights', models.BooleanField(default=False)),
                ('should_be_public', models.BooleanField(default=True)),
                ('min_followers', models.IntegerField(blank=True, null=True)),
                ('max_followers', models.IntegerField(blank=True, null=True)),
                ('should_have_post_in_period', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
