# Generated by Django 3.2 on 2024-10-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0029_auto_20241026_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='servers',
        ),
        migrations.AddField(
            model_name='bulkcampaign',
            name='servers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessionbot.server'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='97c39e82-937b-11ef-af7e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='97c39e82-937b-11ef-af7e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
