# Generated by Django 3.2 on 2024-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0030_auto_20241026_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='fa36f568-9518-11ef-b1a6-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='fa36f568-9518-11ef-b1a6-047c1611323a', max_length=50000, unique=True),
        ),
    ]
