# Generated by Django 3.2 on 2024-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0031_auto_20241028_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='202f8b0d-9519-11ef-bc57-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='202f8b0d-9519-11ef-bc57-047c1611323a', max_length=50000, unique=True),
        ),
    ]
