# Generated by Django 3.2 on 2024-10-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0032_auto_20241028_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='132bfae7-95c2-11ef-bdf9-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='132bfae7-95c2-11ef-bdf9-047c1611323a', max_length=50000, unique=True),
        ),
    ]
