# Generated by Django 3.2 on 2024-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0033_auto_20241029_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='92b63ac3-9c32-11ef-b539-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='92b63ac3-9c32-11ef-b539-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
