# Generated by Django 3.2 on 2024-11-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0034_auto_20241106_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='6c939c29-9cdb-11ef-8a95-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='6c939c29-9cdb-11ef-8a95-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
