# Generated by Django 3.2 on 2024-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0035_auto_20241107_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcampaign',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok')], db_index=True, default='instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='childbot',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok')], max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='08886bde-9ce1-11ef-aa48-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='08886bde-9ce1-11ef-aa48-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
