# Generated by Django 3.2 on 2024-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0036_auto_20241107_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='ed336ef6-9cfe-11ef-8a7b-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ed336ef6-9cfe-11ef-8a7b-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
