# Generated by Django 3.2 on 2024-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0037_auto_20241107_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='420aed15-a016-11ef-9a04-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='420aed15-a016-11ef-9a04-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
