# Generated by Django 3.2 on 2024-11-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0038_auto_20241111_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='38b74513-a0eb-11ef-b108-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='38b74513-a0eb-11ef-b108-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
