# Generated by Django 3.2 on 2024-11-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0039_auto_20241112_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='aa7bee81-a18c-11ef-a5fc-b42e9910d1a0', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='aa7bee81-a18c-11ef-a5fc-b42e9910d1a0', max_length=50000, unique=True),
        ),
    ]
