# Generated by Django 3.2 on 2024-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0040_auto_20241113_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='a0f97af8-a1f0-11ef-b28e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='a0f97af8-a1f0-11ef-b28e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
