# Generated by Django 5.1.1 on 2024-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0041_auto_20241113_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='b9463b9d-a1f2-11ef-a0d6-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='b9463b9d-a1f2-11ef-a0d6-047c1611323a', max_length=50000, unique=True),
        ),
    ]
