# Generated by Django 3.2 on 2024-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0042_alter_task_ref_id_alter_task_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='60445c56-a274-11ef-ab3e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='60445c56-a274-11ef-ab3e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
