# Generated by Django 5.1.1 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0043_auto_20241114_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetask',
            name='max_requests_per_day',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='max_threads',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='5a156542-a276-11ef-8dd3-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='5a156542-a276-11ef-8dd3-047c1611323a', max_length=50000, unique=True),
        ),
    ]
