# Generated by Django 5.1.1 on 2024-11-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0044_scrapetask_max_requests_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessionbot.server'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='3d20d057-a27c-11ef-8f29-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='3d20d057-a27c-11ef-8f29-047c1611323a', max_length=50000, unique=True),
        ),
    ]
