# Generated by Django 5.1.1 on 2024-11-14 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0045_task_server_alter_task_ref_id_alter_task_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 11, 14, 17, 2, 25, 435156))),
                ('message', models.TextField()),
                ('label', models.CharField(max_length=5000)),
                ('end_point', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='500b1e4c-a280-11ef-9dcb-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='500b1e4c-a280-11ef-9dcb-047c1611323a', max_length=50000, unique=True),
        ),
    ]
