# Generated by Django 5.1.1 on 2024-11-14 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0046_logs_alter_task_ref_id_alter_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 17, 32, 10, 285409)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='77e80dcd-a284-11ef-976e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='77e80dcd-a284-11ef-976e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
