# Generated by Django 3.2 on 2024-11-15 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0049_auto_20241115_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 15, 2, 36, 571554)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='bd91bc5b-a338-11ef-838b-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='bd91bc5b-a338-11ef-838b-047c1611323a', max_length=50000, unique=True),
        ),
    ]
