# Generated by Django 5.1.1 on 2024-11-15 11:05

import datetime
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0050_auto_20241115_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='location',
        ),
        migrations.AddField(
            model_name='logs',
            name='identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='google_drive_root_folder_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_after',
            field=models.IntegerField(blank=True, help_text='Enter the number of hours to repeat the task after', null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='target_location',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 16, 5, 29, 840622)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='869ce74d-a341-11ef-bc34-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='869ce74d-a341-11ef-bc34-047c1611323a', max_length=50000, unique=True),
        ),
    ]
