# Generated by Django 5.1.1 on 2024-11-16 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0051_remove_todo_location_logs_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='bots',
            new_name='childbots',
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 16, 9, 51, 895933)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='4d391ee9-a40b-11ef-9bbf-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4d391ee9-a40b-11ef-9bbf-047c1611323a', max_length=50000, unique=True),
        ),
    ]
