# Generated by Django 3.2 on 2024-11-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0052_rename_bots_todo_childbots_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 17, 29, 14, 947083)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='64390c76-a416-11ef-8491-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='64390c76-a416-11ef-8491-047c1611323a', max_length=50000, unique=True),
        ),
    ]
