# Generated by Django 5.1.1 on 2024-11-18 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0053_auto_20241116_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alloted_bots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 20, 31, 28, 575889)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='2dffe7ad-a5c2-11ef-bae0-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='2dffe7ad-a5c2-11ef-bae0-047c1611323a', max_length=50000, unique=True),
        ),
    ]
