# Generated by Django 5.1.1 on 2024-11-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0054_task_alloted_bots_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 17, 32, 33, 148943)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='59995969-a672-11ef-a91d-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='59995969-a672-11ef-a91d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
