# Generated by Django 5.1.1 on 2024-11-19 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0055_alter_logs_timestamp_alter_task_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcampaign',
            name='proxies',
            field=models.ManyToManyField(null=True, related_name='proxies', to='sessionbot.proxy'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 17, 33, 16, 974631)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='73b89e75-a672-11ef-a825-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='73b89e75-a672-11ef-a825-047c1611323a', max_length=50000, unique=True),
        ),
    ]
