# Generated by Django 5.1.1 on 2024-11-19 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0056_alter_bulkcampaign_proxies_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcampaign',
            name='proxies',
            field=models.ManyToManyField(blank=True, null=True, related_name='proxies', to='sessionbot.proxy'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 17, 33, 31, 679012)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='7c7c5461-a672-11ef-8d99-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='7c7c5461-a672-11ef-8d99-047c1611323a', max_length=50000, unique=True),
        ),
    ]
