# Generated by Django 3.2 on 2024-11-22 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0057_alter_bulkcampaign_proxies_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 12, 57, 11, 339791)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='61105c61-a8a7-11ef-a1b8-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='61105c61-a8a7-11ef-a1b8-047c1611323a', max_length=50000, unique=True),
        ),
    ]
