# Generated by Django 3.2 on 2024-11-22 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0058_auto_20241122_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 15, 34, 7, 655214)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='4da24cc4-a8bd-11ef-9ac5-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4da24cc4-a8bd-11ef-9ac5-047c1611323a', max_length=50000, unique=True),
        ),
    ]
