# Generated by Django 3.2 on 2024-11-25 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0059_auto_20241122_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 15, 2, 22, 301757)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='5d318973-ab14-11ef-9379-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='5d318973-ab14-11ef-9379-047c1611323a', max_length=50000, unique=True),
        ),
    ]
