# Generated by Django 3.2 on 2024-12-12 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0061_auto_20241125_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 36, 29, 879246)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='546f8611-b87d-11ef-90f3-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='546f8611-b87d-11ef-90f3-047c1611323a', max_length=50000, unique=True),
        ),
    ]
