# Generated by Django 3.2 on 2024-12-13 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0062_auto_20241212_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 13, 51, 31, 955649)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='7339fd91-b92f-11ef-ac93-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='7339fd91-b92f-11ef-ac93-047c1611323a', max_length=50000, unique=True),
        ),
    ]
