# Generated by Django 5.1.1 on 2024-12-13 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0063_auto_20241213_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbot',
            name='proxy_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 13, 18, 12, 18, 900420)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='e188229f-b953-11ef-91cd-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='e188229f-b953-11ef-91cd-047c1611323a', max_length=50000, unique=True),
        ),
    ]
