# Generated by Django 3.2 on 2024-12-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0064_childbot_proxy_url_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 16, 18, 54, 17, 411826)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='3debe176-bbb5-11ef-822b-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='3debe176-bbb5-11ef-822b-047c1611323a', max_length=50000, unique=True),
        ),
    ]
