# Generated by Django 5.1.1 on 2024-12-21 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0066_auto_20241221_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 16, 2, 21, 504230)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='0d39bee2-bf8b-11ef-abcc-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='0d39bee2-bf8b-11ef-abcc-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('cleaning_configuration', models.JSONField(default={})),
                ('enrichment_configuration', models.JSONField(default={})),
                ('storage_configuration', models.JSONField(default={})),
                ('scrape_tasks', models.ManyToManyField(to='sessionbot.scrapetask')),
            ],
        ),
    ]
