# Generated by Django 5.1.1 on 2024-12-23 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0067_alter_logs_timestamp_alter_task_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], default='instagram'),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], db_index=True, default='instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='childbot',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 9, 35, 550921)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c68812d2-c126-11ef-941a-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c68812d2-c126-11ef-941a-047c1611323a', max_length=50000, unique=True),
        ),
    ]
