# Generated by Django 5.1.1 on 2024-12-23 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0068_todo_service_alter_bulkcampaign_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 17, 11, 18, 223014)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='03ba9770-c127-11ef-8448-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='03ba9770-c127-11ef-8448-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], default='instagram', max_length=500),
        ),
    ]
