# Generated by Django 5.1.1 on 2024-12-23 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0069_alter_logs_timestamp_alter_task_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner')], default='instagram', max_length=500),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 18, 5, 58, 758314)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='a7146687-c12e-11ef-83be-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='a7146687-c12e-11ef-83be-047c1611323a', max_length=50000, unique=True),
        ),
    ]
