# Generated by Django 3.2 on 2024-12-27 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0071_auto_20241226_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 14, 33, 4, 952336)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='92f34a7f-c435-11ef-9514-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='92f34a7f-c435-11ef-9514-047c1611323a', max_length=50000, unique=True),
        ),
    ]
