# Generated by Django 3.2 on 2025-01-06 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0072_auto_20241227_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 21, 51, 53, 949215)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='8862e31e-cc4e-11ef-8a3e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='8862e31e-cc4e-11ef-8a3e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
