# Generated by Django 5.1.1 on 2025-01-07 10:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0073_auto_20250106_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessionbot.audience'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 15, 47, 24, 174752)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c765f575-cce4-11ef-b322-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c765f575-cce4-11ef-b322-047c1611323a', max_length=50000, unique=True),
        ),
    ]
