# Generated by Django 5.1.1 on 2025-01-07 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0074_bulkcampaign_audience_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='filters',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 18, 27, 18, 960549)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='1e565078-ccfb-11ef-b0ce-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='1e565078-ccfb-11ef-b0ce-047c1611323a', max_length=50000, unique=True),
        ),
    ]
