# Generated by Django 3.2 on 2025-01-11 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0075_bulkcampaign_filters_alter_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 23, 14, 1, 505784)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='d58140a9-d047-11ef-bbd8-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='d58140a9-d047-11ef-bbd8-047c1611323a', max_length=50000, unique=True),
        ),
    ]
