# Generated by Django 3.2 on 2025-01-11 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0076_auto_20250111_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='info',
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='versions',
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 23, 17, 19, 594159)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='4b9323ba-d048-11ef-958e-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4b9323ba-d048-11ef-958e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
