# Generated by Django 3.2 on 2025-01-11 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0077_auto_20250111_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 23, 22, 21, 701207)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='ffa5045d-d048-11ef-8c03-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ffa5045d-d048-11ef-8c03-047c1611323a', max_length=50000, unique=True),
        ),
    ]
