# Generated by Django 3.2 on 2025-01-13 09:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0078_auto_20250111_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('09fe3f1f-d18e-11ef-b57c-047c1611323a'), unique=True),
        ),
       
    ]
