# Generated by Django 3.2 on 2025-01-13 09:50

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0079_auto_20250113_1409'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddd04447-d193-11ef-906d-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddcfcf19-d193-11ef-865d-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 14, 50, 48, 358611)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='reference id of the job i.e. campaign or audience or scrape task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ddd01d37-d193-11ef-9edd-047c1611323a', max_length=50000, unique=True),
        ),
    ]
