# Generated by Django 3.2 on 2025-01-22 12:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0080_auto_20250113_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bd8cf96b-d8c0-11ef-80a1-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 17, 59, 39, 725788)),
        ),
        
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='bd8d478b-d8c0-11ef-ba93-047c1611323a', max_length=50000, unique=True),
        ),
    ]
