# Generated by Django 3.2 on 2025-01-22 13:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0081_auto_20250122_1759'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('325c8a92-d8c1-11ef-b3b2-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 2, 55, 701805)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='325cd8b6-d8c1-11ef-8d6d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
