# Generated by Django 3.2 on 2025-01-22 13:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0084_auto_20250122_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahousesyncstatus',
            name='object_id',
        ),
        migrations.AddField(
            model_name='datahousesyncstatus',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('83616dee-d8c3-11ef-8df2-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 19, 30, 622748)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8360f73e-d8c3-11ef-94fb-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='8361bc0e-d8c3-11ef-94a6-047c1611323a', max_length=50000, unique=True),
        ),
    ]
