# Generated by Django 3.2 on 2025-01-22 13:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0085_auto_20250122_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahousesyncstatus',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91d85158-d8c3-11ef-9e1b-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 19, 54, 890997)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('91d7dc24-d8c3-11ef-93e4-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='91d8c683-d8c3-11ef-9583-047c1611323a', max_length=50000, unique=True),
        ),
    ]
