# Generated by Django 3.2 on 2025-01-22 13:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0086_auto_20250122_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbot',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c4237510-d8c3-11ef-864e-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 21, 19, 268511)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c422ffe1-d8c3-11ef-882c-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c423c32f-d8c3-11ef-9714-047c1611323a', max_length=50000, unique=True),
        ),
    ]
