# Generated by Django 3.2 on 2025-01-22 13:24

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0087_auto_20250122_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34a1652c-d8c4-11ef-82c2-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 18, 24, 27, 998678)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34a0c8f0-d8c4-11ef-acd2-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='34a1b350-d8c4-11ef-ae72-047c1611323a', max_length=50000, unique=True),
        ),
    ]
