# Generated by Django 3.2 on 2025-01-29 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0089_auto_20250122_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='sessionbot.job')),
            ],
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f2fe5acd-de57-11ef-af69-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 20, 44, 39, 209141)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f2fca355-de57-11ef-8799-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='f2fea8fa-de57-11ef-b83d-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobs', models.ManyToManyField(to='sessionbot.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.ManyToManyField(to='sessionbot.Task'),
        ),
    ]
