# Generated by Django 3.2 on 2025-01-30 15:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0090_auto_20250129_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 1, 30, 20, 11, 15, 921942))),
                ('message', models.TextField()),
                ('label', models.CharField(max_length=5000)),
                ('end_point', models.CharField(max_length=500)),
                ('identifier', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('735a9588-df1c-11ef-b465-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('735a20a5-df1c-11ef-a50f-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='735b0ad5-df1c-11ef-9546-047c1611323a', max_length=50000, unique=True),
        ),
    ]
