# Generated by Django 3.2 on 2025-01-30 15:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0091_auto_20250130_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('9ac870b5-df1c-11ef-ac88-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ac7d498-df1c-11ef-95de-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 20, 12, 22, 68037)),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ac75f45-df1c-11ef-95b1-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='9ac82287-df1c-11ef-857d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
