# Generated by Django 3.2 on 2025-01-30 16:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0092_auto_20250130_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d6b1cd7-df28-11ef-a51a-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 21, 36, 33, 81143)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('5d6be027-df28-11ef-aab9-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d6a93e4-df28-11ef-839a-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='reference id of the job i.e. campaign or audience or scrape task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='5d6b9207-df28-11ef-9a19-047c1611323a', max_length=50000, unique=True),
        ),
    ]
