# Generated by Django 3.2 on 2025-01-30 17:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0093_auto_20250130_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 3, 55, 676355)),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('307ba1cc-df2c-11ef-b5d0-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 3, 55, 678356)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('307c51ce-df2c-11ef-898b-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('307b2c9b-df2c-11ef-9e1f-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='307c03a2-df2c-11ef-af3b-047c1611323a', max_length=50000, unique=True),
        ),
    ]
