# Generated by Django 3.2 on 2025-01-30 17:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0094_auto_20250130_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='delete',
            new_name='_delete',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('536ead23-df31-11ef-9089-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 40, 41, 796848)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('536f4962-df31-11ef-b3a8-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('536e10e3-df31-11ef-b531-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 40, 41, 794848)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='536efb41-df31-11ef-bd1e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
