# Generated by Django 3.2 on 2025-01-30 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0095_auto_20250130_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahousesyncstatus',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessionbot.server'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e2a9d14-df33-11ef-847c-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 53, 58, 268552)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2e2b3953-df33-11ef-9486-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e2a27e4-df33-11ef-9d2e-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 22, 53, 58, 266552)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='2e2aeb33-df33-11ef-bb48-047c1611323a', max_length=50000, unique=True),
        ),
    ]
