# Generated by Django 3.2 on 2025-01-31 13:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0096_auto_20250130_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0f0929d1-dfd6-11ef-9429-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 18, 19, 54, 6888)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('0f09c611-dfd6-11ef-8d0c-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0f088d92-dfd6-11ef-a20d-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 18, 19, 54, 4888)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='0f0977f3-dfd6-11ef-987a-047c1611323a', max_length=50000, unique=True),
        ),
    ]
