# Generated by Django 3.2 on 2025-01-31 13:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0099_auto_20250131_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childbot',
            name='cookie',
        ),
        migrations.RemoveField(
            model_name='childbot',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='childbot',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd393f94-dfda-11ef-a24a-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 18, 55, 11, 606680)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('fd39dbf6-dfda-11ef-8c2b-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd38ca76-dfda-11ef-9b15-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd387c4e-dfda-11ef-925d-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 18, 55, 11, 604678)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='fd398dc5-dfda-11ef-a7d5-047c1611323a', max_length=50000, unique=True),
        ),
    ]
