# Generated by Django 3.2 on 2025-01-31 14:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0100_auto_20250131_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkcampaign',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2d0a2533-dfe3-11ef-80ce-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 53, 47, 802456)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2d0ac172-dfe3-11ef-8574-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2d0988f4-dfe3-11ef-8235-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2d093ad3-dfe3-11ef-995c-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 53, 47, 800456)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='2d0a7352-dfe3-11ef-ac22-047c1611323a', max_length=50000, unique=True),
        ),
    ]
