# Generated by Django 3.2 on 2025-01-31 14:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0101_auto_20250131_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='4fd6ce87-dfe3-11ef-8df8-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4fd6ce86-dfe3-11ef-b126-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 54, 46, 186259)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('4fd76ac4-dfe3-11ef-bc4a-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4fd650f7-dfe3-11ef-99c4-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4fd602d7-dfe3-11ef-91fe-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 54, 46, 184259)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4fd71ca4-dfe3-11ef-b847-047c1611323a', max_length=50000, unique=True),
        ),
    ]
