# Generated by Django 3.2 on 2025-02-01 09:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0103_auto_20250131_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cba73ee3-e081-11ef-9124-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='cba73ee4-e081-11ef-9d29-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 14, 49, 14, 395318)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('cba7db23-e081-11ef-a435-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cba67b94-e081-11ef-94ec-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 14, 49, 14, 393318)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='cba78d04-e081-11ef-b3f2-047c1611323a', max_length=50000, unique=True),
        ),
    ]
