# Generated by Django 3.2 on 2025-02-05 10:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0104_auto_20250201_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_link', models.URLField(unique=True)),
                ('spreadsheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='proxy',
            name='type',
            field=models.CharField(choices=[('static', 'Static'), ('rotating', 'Rotating')], default='static', max_length=20),
        ),
        migrations.AlterField(
            model_name='audience',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], default='instagram', max_length=500),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e94b0ee4-e3ab-11ef-9a6b-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], db_index=True, default='instagram', max_length=100),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='e94b0ee5-e3ab-11ef-841a-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='childbot',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 15, 28, 16, 473782)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('e94bab24-e3ab-11ef-a53d-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapetask',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], max_length=5000),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e94a4b94-e3ab-11ef-b33f-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 15, 28, 16, 472783)),
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='e94b5d01-e3ab-11ef-8603-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], default='instagram', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='connected_to_server',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='max_threads',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_blacklisted',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_protocol',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_type',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='tagged_bad_on',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='ua_string',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='verified',
        ),
    ]
