# Generated by Django 3.2 on 2025-02-05 10:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0105_auto_20250205_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncedsheet',
            old_name='google_sheet_link',
            new_name='google_spreadsheet_url',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34ff4c7e-e3ad-11ef-85a2-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='34ff7394-e3ad-11ef-b330-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 15, 37, 32, 980857)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('34ffe8be-e3ad-11ef-851c-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('34fe8934-e3ad-11ef-a147-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 15, 37, 32, 979857)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='34ffc1b2-e3ad-11ef-89aa-047c1611323a', max_length=50000, unique=True),
        ),
    ]
