# Generated by Django 3.2 on 2025-02-11 12:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0106_auto_20250205_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', models.JSONField()),
                ('range_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.RemoveField(
            model_name='log',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a5a9784-e873-11ef-8d0e-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='4a5a9785-e873-11ef-b004-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 17, 25, 33, 827253)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('4a5d1713-e873-11ef-8063-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a5a9783-e873-11ef-a9ff-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 17, 25, 33, 810880)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='4a5a9786-e873-11ef-8707-047c1611323a', max_length=50000, unique=True),
        ),
    ]
