# Generated by Django 3.2 on 2025-02-26 14:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0107_auto_20250211_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbot',
            name='failed_api_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childbot',
            name='interactions_so_far',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childbot',
            name='is_challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childbot',
            name='is_scraper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childbot',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childbot',
            name='scraped_so_far',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childbot',
            name='successful_api_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c9a460f1-f450-11ef-8285-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='c9a460f2-f450-11ef-a8fa-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 19, 48, 48, 937888)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('c9a52440-f450-11ef-808d-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c9a37601-f450-11ef-b70e-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 19, 48, 48, 935888)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c9a4d620-f450-11ef-9ad1-047c1611323a', max_length=50000, unique=True),
        ),
    ]
