# Generated by Django 3.2 on 2025-02-27 11:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0108_auto_20250226_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetask',
            name='bot_status',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='failed_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='media_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='media_stored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='requests_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='scraped_so_far',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapetask',
            name='successful_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('35e96fdf-f4fe-11ef-921e-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='35e96fe0-f4fe-11ef-a637-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 16, 30, 13, 518622)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('35ea332d-f4fe-11ef-ab20-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('35e8ac7f-f4fe-11ef-a950-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 16, 30, 13, 516622)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='35e9e50c-f4fe-11ef-a85e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
