# Generated by Django 3.2 on 2025-04-16 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0112_auto_20250307_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='disk_usage',
            new_name='cpu_percent',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='ram_usage',
            new_name='disk_percent',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tm_state',
        ),
        migrations.AddField(
            model_name='server',
            name='health',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'UnHealthy')], default='healthy', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('edit_profile', 'edit_profile')], default='post', max_length=500),
        ),
        migrations.AddField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ea4b7c36-1acd-11f0-82e0-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='ea4ba528-1acd-11f0-b297-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 19, 20, 15, 1545)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ea4cf5dd-1acd-11f0-a369-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='instance_type',
            field=models.CharField(choices=[('main', 'Main'), ('data_server', 'DataServer'), ('storage_server', 'StorageServer'), ('central_server', 'CentralServer'), ('worker_server', 'WorkerServer'), ('dev_server', 'DevelopmentServer')], max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ea4969a3-1acd-11f0-ba2b-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 19, 20, 14, 997223)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ea4c4d0b-1acd-11f0-a4ad-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='sessionbot.server')),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='sessionbot.server')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('resource', 'Resource Usage')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sessionbot.server')),
            ],
        ),
    ]
