# Generated by Django 3.2 on 2025-03-22 10:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0112_auto_20250307_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('edit_profile', 'edit_profile')], default='post', max_length=500),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bf35739c-070c-11f0-9606-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='bf35a17a-070c-11f0-8027-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 59, 37, 749122)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('bf364115-070c-11f0-88d3-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bf34c458-070c-11f0-94db-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 59, 37, 747120)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='bf35f2e7-070c-11f0-b940-047c1611323a', max_length=50000, unique=True),
        ),
    ]
