# Generated by Django 3.2 on 2025-04-09 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0115_auto_20250409_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartbeat',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='resourceusage',
            name='server_name',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='sessionbot.server'),
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_usage', to='sessionbot.server'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae13a423-1541-11f0-862d-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='ae13cb4a-1541-11f0-b0de-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 17, 53, 48, 612111)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae147c9d-1541-11f0-ab5d-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ae128e53-1541-11f0-8776-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 17, 53, 48, 610605)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ae141aa1-1541-11f0-9c03-047c1611323a', max_length=50000, unique=True),
        ),
    ]
