# Generated by Django 3.2 on 2025-04-09 15:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0116_auto_20250409_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='disk_usage',
            new_name='cpu_percent',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='ram_usage',
            new_name='disk_percent',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tm_state',
        ),
        migrations.AddField(
            model_name='server',
            name='ram_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b5836f67-1555-11f0-95bc-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='b5836f68-1555-11f0-9e1c-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 20, 17, 11, 22485)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('b58423db-1555-11f0-a629-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='instance_type',
            field=models.CharField(choices=[('main', 'Main'), ('data_server', 'DataServer'), ('storage_server', 'StorageServer'), ('central_server', 'CentralServer'), ('worker_server', 'WorkerServer'), ('dev_server', 'DevelopmentServer')], max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b582989d-1555-11f0-b018-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 20, 17, 11, 20484)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='b583d5ab-1555-11f0-9e5f-047c1611323a', max_length=50000, unique=True),
        ),
    ]
