# Generated by Django 3.2 on 2025-04-09 17:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0117_auto_20250409_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='health',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'UnHealthy')], default='healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b72769bd-156a-11f0-a229-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='b72791ed-156a-11f0-9eab-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 22, 47, 33, 206584)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7282e39-156a-11f0-b7e2-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b726928d-156a-11f0-b622-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 22, 47, 33, 204584)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='b727e019-156a-11f0-93ba-047c1611323a', max_length=50000, unique=True),
        ),
    ]
