# Generated by Django 3.2 on 2025-05-15 18:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0117_auto_20250503_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d66072fe-31bb-11f0-97b8-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='d6609a0a-31bb-11f0-a148-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 23, 38, 47, 390801)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('d6627733-31bb-11f0-8cea-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d65a9ea8-31bb-11f0-a58a-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 23, 38, 47, 386730)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='d661b110-31bb-11f0-82b5-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
