# Generated by Django 3.2 on 2025-07-04 13:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0118_auto_20250515_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audience',
            old_name='cleaning_configuration',
            new_name='workflow_steps',
        ),
        migrations.RemoveField(
            model_name='audience',
            name='enrichment_configuration',
        ),
        migrations.AddField(
            model_name='audience',
            name='prompt',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('256c505f-58db-11f0-9306-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='256c78d8-58db-11f0-8318-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 18, 31, 9, 752798)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('256dc215-58db-11f0-ba6b-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='instance_type',
            field=models.CharField(choices=[('main', 'Main'), ('data_server', 'DataServer'), ('storage_server', 'StorageServer'), ('central_server', 'CentralServer'), ('worker_server', 'WorkerServer'), ('dev_server', 'DevelopmentServer'), ('reporting_and_analytics_server', 'Reporting and Analytics Server')], max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('256a46f3-58db-11f0-b06c-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 18, 31, 9, 748628)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='256d47cc-58db-11f0-a11c-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
