# Generated by Django 3.2 on 2025-06-16 07:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0119_auto_20250409_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('341c9232-4a81-11f0-9594-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='341c9233-4a81-11f0-808e-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 12, 12, 3, 406125)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('341d5bc4-4a81-11f0-88a4-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='instance_type',
            field=models.CharField(choices=[('main', 'Main'), ('data_server', 'DataServer'), ('storage_server', 'StorageServer'), ('central_server', 'CentralServer'), ('worker_server', 'WorkerServer'), ('dev_server', 'DevelopmentServer'), ('reporting_and_analytics_server', 'Reporting and Analytics Server')], max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('341b3273-4a81-11f0-9721-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 12, 12, 3, 403966)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='341d0772-4a81-11f0-ab92-047c1611323a', max_length=50000, unique=True),
        ),
    ]
