# Generated by Django 5.2 on 2025-07-15 18:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0120_auto_20250616_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e4ece04-61a6-11f0-a0ad-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='2e4ece05-61a6-11f0-a84f-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 23, 4, 41, 790733)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2e4f6a8b-61a6-11f0-bdb6-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e4de056-61a6-11f0-b150-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 23, 4, 41, 788730)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='2e4f1c45-61a6-11f0-97b6-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.CreateModel(
            name='AppClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the app clone (e.g., 'WhatsApp Clone 1').", max_length=255)),
                ('package_name', models.CharField(help_text="The unique package name of the cloned application (e.g., 'com.whatsapp.clone1').", max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time when this app clone record was created.')),
                ('device', models.ForeignKey(help_text='The device on which this app clone is installed.', on_delete=django.db.models.deletion.CASCADE, related_name='app_clones', to='sessionbot.device')),
            ],
            options={
                'verbose_name': 'App Clone',
                'verbose_name_plural': 'App Clones',
                'ordering': ['-created_on', 'name'],
            },
        ),
    ]
