# Generated by Django 3.2 on 2025-07-09 11:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0121_auto_20250708_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddfd788a-5cbb-11f0-ac20-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='ddfda51c-5cbb-11f0-bda0-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 16, 57, 20, 162236)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('ddff5159-5cbb-11f0-ab1d-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddfaa360-5cbb-11f0-9f4d-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 16, 57, 20, 157921)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ddfea8cd-5cbb-11f0-9b7c-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
