# Generated by Django 5.2 on 2025-07-16 10:57

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0124_alter_audience_uuid_alter_bulkcampaign_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9b743c27-6233-11f0-acea-047c1611323a'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='9b743c28-6233-11f0-b513-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 15, 57, 3, 946997)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('9b74e996-6233-11f0-acca-047c1611323a'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9b7370f1-6233-11f0-adba-047c1611323a'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 15, 57, 3, 945946)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='9b748ec2-6233-11f0-8f2d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
