# Generated by Django 3.2 on 2025-08-11 14:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0145_auto_20250811_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3e7a3397-76c2-11f0-9f0c-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='3e7a5b4f-76c2-11f0-9b05-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 19, 48, 29, 251889)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('3e7bcbf2-76c2-11f0-8a0c-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3e7820e2-76c2-11f0-ab0c-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 11, 19, 48, 29, 247774)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='3e7b2b35-76c2-11f0-b2ca-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
