# Generated by Django 3.2 on 2025-08-12 11:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0153_auto_20250812_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskErrorSummary',
            fields=[
                ('task_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('critical_errors', models.JSONField(default=list)),
                ('attempt_failed_errors', models.JSONField(default=list)),
                ('current_status', models.CharField(default='unknown', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('15ad3562-7770-11f0-ad0c-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='15ad601d-7770-11f0-954a-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 16, 32, 53, 230579)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('15aecf7f-7770-11f0-82cb-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('15aafadb-7770-11f0-8d10-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 16, 32, 53, 226415)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='15ae2cd8-7770-11f0-a846-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
