# Generated by Django 3.2 on 2025-08-12 12:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0157_auto_20250812_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskerrorsummary',
            name='bot_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskerrorsummary',
            name='issue_status',
            field=models.CharField(default='pendding', max_length=50),
        ),
        migrations.AddField(
            model_name='taskerrorsummary',
            name='scrape_task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('675d1b0c-7775-11f0-83d9-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='675d4305-7775-11f0-a4c9-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 10, 57, 760507)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('675e69d2-7775-11f0-863b-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('675b1c44-7775-11f0-b77e-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 10, 57, 757270)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='675deb61-7775-11f0-bb90-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
