# Generated by Django 3.2 on 2025-08-12 12:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0159_auto_20250812_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('03ede29c-777b-11f0-8dc8-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='03ee0be3-777b-11f0-8953-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 51, 7, 919451)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('03ef7b96-777b-11f0-af8e-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('03ebf819-777b-11f0-9b30-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 17, 51, 7, 915309)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='03eed9c2-777b-11f0-ba04-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
