# Generated by Django 3.2 on 2025-08-13 14:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sessionbot', '0179_auto_20250813_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('20325b21-7853-11f0-aab3-f079596d88b9'), unique=True),
        ),
        migrations.AlterField(
            model_name='bulkcampaign',
            name='uuid',
            field=models.CharField(default='203282d2-7853-11f0-94ba-f079596d88b9', max_length=50000, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 38, 6, 637227)),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2033d6b3-7853-11f0-b747-f079596d88b9'), null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('20301b1a-7853-11f0-b7eb-f079596d88b9'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 19, 38, 6, 633799)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='20332938-7853-11f0-8006-f079596d88b9', max_length=50000, unique=True),
        ),
    ]
