# Generated by Django 5.2 on 2025-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AI Service Provider',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imap_email_host', models.CharField(max_length=200, unique=True)),
                ('imap_email_port', models.PositiveIntegerField()),
                ('imap_email_username', models.EmailField(max_length=100, unique=True)),
                ('imap_email_password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Email Provider',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Phone Number Provider',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('api_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proxy Provider',
                'abstract': False,
            },
        ),
    ]
