# Generated by Django 5.2 on 2025-07-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
        ('sessionbot', '0123_alter_audience_uuid_alter_bulkcampaign_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the app clone (e.g., 'WhatsApp Clone 1').", max_length=255)),
                ('package_name', models.CharField(help_text="The unique package name of the cloned application (e.g., 'com.whatsapp.clone1').", max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time when this app clone record was created.')),
                ('device', models.ForeignKey(help_text='The device on which this app clone is installed.', on_delete=django.db.models.deletion.CASCADE, related_name='app_clones', to='sessionbot.device')),
            ],
            options={
                'verbose_name': 'App Clone',
                'verbose_name_plural': 'App Clones',
                'ordering': ['-created_on', 'name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'package_name'), name='unique_device_package')],
            },
        ),
    ]
