# Generated by Django 3.2 on 2025-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreationjob',
            name='after_creation_logic',
            field=models.JSONField(blank=True, default=list, help_text='Sequence of operations to perform after account creation'),
        ),
        migrations.AlterField(
            model_name='accountcreationjob',
            name='phone_config',
            field=models.JSONField(blank=True, default=dict, help_text='Phone provider configuration (country, city, etc.)'),
        ),
        migrations.AlterField(
            model_name='accountcreationjob',
            name='proxy_config',
            field=models.JSONField(blank=True, default=dict, help_text='Proxy provider configuration (country, city, etc.)'),
        ),
        migrations.AlterField(
            model_name='accountcreationjob',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Job execution settings'),
        ),
    ]
