# Generated by Django 5.2 on 2025-07-15 18:33

import creator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_appclone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the account creation job', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', help_text='Current job status', max_length=20)),
                ('profiling', models.JSONField(blank=True, default=dict, help_text='Profile setup configuration', validators=[creator.models.validate_profiling_config])),
                ('posting', models.JSONField(blank=True, default=dict, help_text='Content posting configuration', validators=[creator.models.validate_posting_config])),
                ('warmup', models.JSONField(blank=True, default=dict, help_text='Account warming configuration', validators=[creator.models.validate_warmup_config])),
                ('two_fa_live_support', models.BooleanField(default=False, help_text='Enable live 2FA support')),
                ('email_provider', models.ForeignKey(blank=True, help_text='Email provider for account creation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.emailprovider')),
                ('phone_provider', models.ForeignKey(blank=True, help_text='Phone number provider for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.phonenumberprovider')),
                ('proxy_provider', models.ForeignKey(blank=True, help_text='Proxy provider for network routing', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.proxyprovider')),
            ],
            options={
                'verbose_name': 'Account Creation Job',
                'verbose_name_plural': 'Account Creation Jobs',
                'ordering': ['-created_on'],
            },
        ),
    ]
