# Generated by Django 5.2 on 2025-07-15 18:40

import creator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_accountcreationjob'),
        ('sessionbot', '0124_alter_audience_uuid_alter_bulkcampaign_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreationjob',
            name='after_creation_steps',
            field=models.JSONField(blank=True, default=dict, help_text='Steps to execute after account creation', validators=[creator.models.validate_after_creation_logic]),
        ),
        migrations.AlterField(
            model_name='accountcreationjob',
            name='name',
            field=models.CharField(help_text='Unique name for the account creation job', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='accountcreationjob',
            name='phone_provider',
            field=models.ForeignKey(blank=True, help_text='Phone provider for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.phonenumberprovider'),
        ),
        migrations.AlterField(
            model_name='aiserviceprovider',
            name='api_key',
            field=models.CharField(help_text='API key for the provider service', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiserviceprovider',
            name='name',
            field=models.CharField(help_text='Unique name for the provider', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aiserviceprovider',
            name='provider_name',
            field=models.CharField(help_text='Name of the service provider', max_length=100, verbose_name='Provider Name'),
        ),
        migrations.AlterField(
            model_name='appclone',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='appclone',
            name='device',
            field=models.ForeignKey(help_text='The device this app clone is installed on', on_delete=django.db.models.deletion.CASCADE, related_name='app_clones', to='sessionbot.device'),
        ),
        migrations.AlterField(
            model_name='appclone',
            name='name',
            field=models.CharField(help_text='The name of the app clone', max_length=255),
        ),
        migrations.AlterField(
            model_name='appclone',
            name='package_name',
            field=models.CharField(help_text='Unique package name of the cloned app', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_host',
            field=models.CharField(help_text='IMAP server hostname', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_password',
            field=models.CharField(help_text='Password for authentication', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_port',
            field=models.PositiveIntegerField(help_text='IMAP server port number'),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='imap_email_username',
            field=models.EmailField(help_text='Email address for authentication', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailprovider',
            name='name',
            field=models.CharField(help_text='Unique name for the email provider', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumberprovider',
            name='api_key',
            field=models.CharField(help_text='API key for the provider service', max_length=255),
        ),
        migrations.AlterField(
            model_name='phonenumberprovider',
            name='name',
            field=models.CharField(help_text='Unique name for the provider', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumberprovider',
            name='provider_name',
            field=models.CharField(help_text='Name of the service provider', max_length=100, verbose_name='Provider Name'),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='api_key',
            field=models.CharField(help_text='API key for the provider service', max_length=255),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='name',
            field=models.CharField(help_text='Unique name for the provider', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='provider_name',
            field=models.CharField(help_text='Name of the service provider', max_length=100, verbose_name='Provider Name'),
        ),
    ]
