# Generated by Django 5.2 on 2025-07-16 10:46

import creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_accountcreationjob_after_creation_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreationjob',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Job execution settings', validators=[creator.models.validate_settings_config]),
        ),
    ]
