# Generated by Django 5.2 on 2025-07-16 10:57

import creator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_accountcreationjob_settings'),
        ('sessionbot', '0125_alter_audience_uuid_alter_bulkcampaign_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcreationjob',
            name='after_creation_steps',
        ),
        migrations.RemoveField(
            model_name='accountcreationjob',
            name='posting',
        ),
        migrations.RemoveField(
            model_name='accountcreationjob',
            name='profiling',
        ),
        migrations.RemoveField(
            model_name='accountcreationjob',
            name='warmup',
        ),
        migrations.AddField(
            model_name='accountcreationjob',
            name='after_creation_logic',
            field=models.JSONField(blank=True, default=list, help_text='Sequence of operations to perform after account creation', validators=[creator.models.validate_after_creation_logic]),
        ),
        migrations.AddField(
            model_name='accountcreationjob',
            name='app_clones',
            field=models.ManyToManyField(help_text='App clones used for account creation', related_name='account_jobs', to='creator.appclone'),
        ),
        migrations.AddField(
            model_name='accountcreationjob',
            name='device',
            field=models.ForeignKey(help_text='Device used for account creation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_jobs', to='sessionbot.device'),
        ),
        migrations.AddField(
            model_name='accountcreationjob',
            name='phone_config',
            field=models.JSONField(blank=True, default=dict, help_text='Phone provider configuration (country, city, etc.)', validators=[creator.models.validate_phone_config]),
        ),
        migrations.AddField(
            model_name='accountcreationjob',
            name='proxy_config',
            field=models.JSONField(blank=True, default=dict, help_text='Proxy provider configuration (country, city, etc.)', validators=[creator.models.validate_proxy_config]),
        ),
    ]
