# Generated by Django 5.2 on 2025-07-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_remove_accountcreationjob_after_creation_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreationjob',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('attendance', 'attendance'), ('twitter', 'twitter'), ('tiktok', 'tiktok'), ('cleaner', 'cleaner'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse')], db_index=True, default='instagram', max_length=50),
        ),
    ]
